### ISSUE TITLE
Batch Folders

### ISSUE THREAD

**Issue by kaprakashr** [kaprakashr/Frooty#20]
Inside the log directory, for every batch new run, create a new folder,

Folder name: **<batch_name_date_time>**
     -> per test case log file
     -> summary file
     -> any other info, put inside same folder

**Comment by sa-ku** [comment]
This issue is fixed, here is the output for reference

/Frooty/LOGS/SMOKE_SANITY_2017-11-050248                        ---> Folder Name

snmp_example_walk_TEST_CASE_001_2017-11-05_02:48:10.log ---> per testcase log file
snmp_example_walk_TEST_CASE_002_2017-11-05_02:48:10.log
snmp_example_get_TEST_CASE_001_2017-11-05_02:48:11.log
snmp_example_get_TEST_CASE_002_2017-11-05_02:48:11.log
snmp_example_get_TEST_CASE_003_2017-11-05_02:48:11.log
snmp_example_get_TEST_CASE_004_2017-11-05_02:48:11.log
SMOKE_SANITY_2017-11-050248.summary                              ---> summary file
