### ISSUE TITLE
Summary file format

### ISSUE THREAD

**Issue by kaprakashr** [kaprakashr/Frooty#21]
New summary file format

------------------------------------------------------
  FROOTY AUTOMATION ENVIRONMENT
------------------------------------------------------

WebLink For results: <>
Result Exported to DB: NO

#-------TEST CASE STATISTICS------------
TOTAL TEST CASES EXECUTED : 3
TOTAL TEST CASES PASSED : 3
TOTAL TEST CASES FAILED : 0
TOTAL TEST CASES BLOCKED: 0

SUCCESS RATE = 100%

#------TEST RUN METRICS---------
TOTAL TIME TAKEN  : HH:MM:SS
snmp_example_walk : HH:MM:SS
snmp_example_get  : HH:MM:SS

#------Diagnostics of Individual Tests-------------
snmp_example_walk--> /root/saroj/TEST/Frooty/LOGS/snmp_example_walk_2017-11-03_11:09:42.log
snmp_example_get---> /root/saroj/TEST/Frooty/LOGS/snmp_example_get_2017-11-03_11:09:43.log
snmp_example_set---> /root/saroj/TEST/Frooty/LOGS/snmp_example_set_2017-11-03_11:09:44.log

#--Topology Details----------
<Printing in JSON Format: Copy this for future use>

**Comment by sa-ku** [comment]
This issue is fixed, Here is the output for reference

SMOKE_SANITY_2017-11-050248.summary  --> summary file

#-------------------------------------------------#
       FROOTY AUTOMATION ENVIRONMENT            
#-------------------------------------------------#
WebLink For results: <>
Result Exported to DB: NO
#-------TEST CASE STATISTICS------------
TOTAL TEST CASES EXECUTED : 6
TOTAL TEST CASES PASSED   : 6
TOTAL TEST CASES FAILED   : 0
TOTAL TEST CASES BLOCKED  : 1

SUCCESS RATE : 100%

#-------TEST RUN METRICS----------------
snmp_example_walk_TEST_CASE_001 : 0:00:00
snmp_example_walk_TEST_CASE_002 : 0:00:01
snmp_example_get_TEST_CASE_001 : 0:00:00
snmp_example_get_TEST_CASE_002 : 0:00:00
snmp_example_get_TEST_CASE_003 : 0:00:00
snmp_example_get_TEST_CASE_004 : 0:00:00
TOTAL TIME TAKEN : 0:00:01

#-------Diagnostics of Individual Tests------
#-------PASSED LOGS---------
1./root/saroj/TEST/Batch_Feature/Frooty/LOGS/SMOKE_SANITY_2017-11-050248/snmp_example_walk_TEST_CASE_001_2017-11-05_02:48:10.log
2./root/saroj/TEST/Batch_Feature/Frooty/LOGS/SMOKE_SANITY_2017-11-050248/snmp_example_walk_TEST_CASE_002_2017-11-05_02:48:10.log
3./root/saroj/TEST/Batch_Feature/Frooty/LOGS/SMOKE_SANITY_2017-11-050248/snmp_example_get_TEST_CASE_001_2017-11-05_02:48:11.log
4./root/saroj/TEST/Batch_Feature/Frooty/LOGS/SMOKE_SANITY_2017-11-050248/snmp_example_get_TEST_CASE_002_2017-11-05_02:48:11.log
5./root/saroj/TEST/Batch_Feature/Frooty/LOGS/SMOKE_SANITY_2017-11-050248/snmp_example_get_TEST_CASE_003_2017-11-05_02:48:11.log
6./root/saroj/TEST/Batch_Feature/Frooty/LOGS/SMOKE_SANITY_2017-11-050248/snmp_example_get_TEST_CASE_004_2017-11-05_02:48:11.log
#-------FAILED LOGS---------
NA
#-------Topology Details----------
{"DEVICE_1": {"username": "abc123", "name": "dut", "ip": "127.0.0.1", "snmp_port": "161", "mode": "telnet", "password": "abc123", "port": "23", "community_string": "public"}}
